name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 定义工作流程的任务
jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/manager-demo:${{ github.sha }} .

      
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/manager-demo:${{ github.sha }}